CREATE DATABASE Q2DQL;
USE Q2DQL;
CREATE TABLE CUSTOMER_DETAILS (
    CUSTOMER_ID VARCHAR(10) NOT NULL,
    CUSTOMER_NAME VARCHAR(30) NOT NULL,
    PHONE_NO VARCHAR(10) NOT NULL,
    CITY VARCHAR(20),
    PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE PET_DETAILS(
PET_ID VARCHAR(5) NOT NULL,
PET_NAME VARCHAR(30) NOT NULL,
PET_TYPE VARCHAR(10) NOT NULL,
BREED VARCHAR(20),
GENDER VARCHAR(10),
AGE_IN_DAYS INT(4),
PRICE DOUBLE(7,2),
PRIMARY KEY(PET_ID)
);
CREATE TABLE PURCHASE_DETAILS(
PURCHASE_ID INT(5),
CUSTOMER_ID VARCHAR(10) NOT NULL,
PET_ID VARCHAR(5) NOT NULL,
PURCHASE_DATE DATE,
TOTAL_AMOUNT_PAID DOUBLE(8,2),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID),
FOREIGN KEY(PET_ID) REFERENCES PET_DETAILS(PET_ID)
);
INSERT INTO CUSTOMER_DETAILS VALUES
('10','GEORGE','9746851234','PUNE'),
('16','FAYIZ','9746861234','KOCHI');
INSERT INTO PET_DETAILS VALUES
('20','BRUNO','DOG','DASH','M','100','5000.00'),
('40','NEYMAR','DOG','DASH','F','100','5000.00');




INSERT INTO PURCHASE_DETAILS VALUES
('20','10','20','2020-12-01',50000.00),
('22','16','40','2020-10-17',10000.00);
INSERT INTO PURCHASE_DETAILS VALUES
('20','10','40','2020-12-01',50000.00);
SELECT * FROM CUSTOMER_DETAILS;
SELECT * FROM PURCHASE_DETAILS;

SELECT q1.CUSTOMER_ID,CUSTOMER_DETAILS.CUSTOMER_NAME,q1.No_of_Pets 
FROM (SELECT * FROM (SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID) AS 'No_of_Pets' FROM PURCHASE_DETAILS GROUP BY CUSTOMER_ID) q2 WHERE No_of_Pets > 1) q1
JOIN CUSTOMER_DETAILS 
WHERE q1.CUSTOMER_ID = CUSTOMER_DETAILS.CUSTOMER_ID ORDER BY q1.CUSTOMER_ID ASC;
